services:
  sqlserver:
    build: .  # Usa el Dockerfile local
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433" 
    restart: unless-stopped
 